version: '2'
services:
  mongodb:
    image: mongo
    container_name: iw_exam_mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_DATABASE=fizz_buzz_collection
    volumes:
    - /opt/iw-exam/data:/data/db
  spring-app:
    container_name: iw_exam_java_rest_api
    build: ./
    command: dockerize -wait tcp://mongodb:27017 -timeout 30s
    restart: always
    ports:
    - "8087:8087"
    depends_on:
    - mongodb
